### ISSUE TITLE
hotp.verify scans before counter

### ISSUE THREAD

**Issue by williamwallacew** [guyht/notp#21]
This is a security issue. Once used, OTP should not be verified as success.
But right now it goes this way:
for(var i = counter - window; i <= counter + window; ++i)

should be:
for(var i = counter; i <= counter + window; ++i)

**Comment by aw** [comment]
:question: @guyht can you confirm this?

**Comment by coolaj86** [comment]
If I understand correctly this is to account for time drift in `TOTP`, which is built atop `HOTP`.

For example: For whatever reason my iPhone is 30 seconds off from the server and I want `TOTP` to validate as long as it's within a total of a 90-second window so I do +/- 30 seconds.

In the case of pure `HOTP` you probably don't want any window at all, so you would set the counter to 0 since neither the device nor the server should increment unless they both agree on success.

If that satisfies your use case, this issue is safe to close.

**Comment by guyht** [comment]
@coolaj86 is correct, you can configure the window to 0, but then if the user accidentally clicks through a code, they will have to reset.

**Comment by williamwallacew** [comment]
I've just damaged my face with facepalms, guys! It's unbelievable, truly.
That's why I've managed to completely rewrite OATH implementation for my own. Because I can't rely on implementation of people, who don't understand the standard workflow of HOTP.

Let me explain you a bit more...
I completely understand, if totp.verify will be implemented like this, but not hotp.verify. This is kinda hi-level function and when you using it, you expect it to act in the right way for hotp.
When you using HOTP, you can't check any value less than counter, because it will return you false positive for OTP, which was used before. This will cause security issue, so attacker can easily pass authentication, just repeating previous value. It is that, what you want?
When you checking HOTP, you should check at least 10 counters forward (usually it goes 30 by default in industrial authentication servers). I may want to set it to 1000 to pass syncronisation workflow with 2 sequential OTPs. That's what I've expected from this function, which named as HOTP.VERIFY (not TOTP.VERIFY, if You've noticed)!
You proposing to set window to 0? So, by using hi-level function, I should use it as low-level, just because you decided to lasy-wrap it for TOTP? Seriously?

If you finally got my point, I will give you the right answer to "What should we do then?"

HOTP.VERIFY should contain this kind of loop:
for(var i = counter; i <= counter + window; ++i)...

TOTP.VERIFY should call hotp.verify with something like that:
var correction = 0;

if(counter<window) {
     correction = counter-window;
}
hotp.verify(token, key, {window: window*2+correction, counter: counter-window-correction});

*where window already calculated as number of steps to check in both sides.

that's the way it should be to avoid use of hacks, like setting window to zero and making multiple calls of hotp.verify, playing with counter. Hope it's clear enough.
