### ISSUE TITLE
notp doesn't work with binary keys

### ISSUE THREAD

**Issue by dooglus** [guyht/notp#7]
Lots of sites generate a random binary string as the key, and base32 encode it.

Your code:
  	var hmac = crypto.createHmac('SHA1', new Buffer(key));

takes the binary key, but treats it as utf8 encoded.

new Buffer(key, 'binary') would be better, but http://nodejs.org/api/buffer.html says that the 'binary' encoding " is deprecated and should be avoided in favor of Buffer objects where possible. This encoding will be removed in future versions of Node.".

So what really needs to happen is for the base32 decode function to decode the string into a buffer rather than a string.

As a test case, try the base32-encoded secret 'ZZZZZZZZZZZZZZZZ' on notp and on google authenticator, and see that they get different results.

**Comment by OhJeez** [comment]
Please close
@miccolis my pull request has been merged into thirty-two, so that's why it works now.

**Comment by guyht** [comment]
Closing.  Thanks @OhJeez
